// ============================================================
// GridBlitz - All 32 NFL Team Seed Data
// ============================================================

import type { PlayStyle, Conference, Division } from '../../simulation/types';

export interface TeamSeedData {
  name: string;
  abbreviation: string;
  city: string;
  mascot: string;
  conference: Conference;
  division: Division;
  primaryColor: string;
  secondaryColor: string;
  offenseRating: number;
  defenseRating: number;
  specialTeamsRating: number;
  playStyle: PlayStyle;
}

export const teamsSeedData: TeamSeedData[] = [
  // ==========================================================
  // AFC EAST
  // ==========================================================
  {
    name: 'Buffalo Bills',
    abbreviation: 'BUF',
    city: 'Buffalo',
    mascot: 'Bills',
    conference: 'AFC',
    division: 'East',
    primaryColor: '#00338D',
    secondaryColor: '#C60C30',
    offenseRating: 90,
    defenseRating: 85,
    specialTeamsRating: 82,
    playStyle: 'pass_heavy',
  },
  {
    name: 'Miami Dolphins',
    abbreviation: 'MIA',
    city: 'Miami',
    mascot: 'Dolphins',
    conference: 'AFC',
    division: 'East',
    primaryColor: '#008E97',
    secondaryColor: '#FC4C02',
    offenseRating: 88,
    defenseRating: 79,
    specialTeamsRating: 78,
    playStyle: 'aggressive',
  },
  {
    name: 'New England Patriots',
    abbreviation: 'NE',
    city: 'New England',
    mascot: 'Patriots',
    conference: 'AFC',
    division: 'East',
    primaryColor: '#002244',
    secondaryColor: '#C60C30',
    offenseRating: 73,
    defenseRating: 76,
    specialTeamsRating: 75,
    playStyle: 'conservative',
  },
  {
    name: 'New York Jets',
    abbreviation: 'NYJ',
    city: 'New York',
    mascot: 'Jets',
    conference: 'AFC',
    division: 'East',
    primaryColor: '#125740',
    secondaryColor: '#FFFFFF',
    offenseRating: 78,
    defenseRating: 83,
    specialTeamsRating: 77,
    playStyle: 'balanced',
  },

  // ==========================================================
  // AFC NORTH
  // ==========================================================
  {
    name: 'Baltimore Ravens',
    abbreviation: 'BAL',
    city: 'Baltimore',
    mascot: 'Ravens',
    conference: 'AFC',
    division: 'North',
    primaryColor: '#241773',
    secondaryColor: '#9E7C0C',
    offenseRating: 92,
    defenseRating: 90,
    specialTeamsRating: 88,
    playStyle: 'run_heavy',
  },
  {
    name: 'Cincinnati Bengals',
    abbreviation: 'CIN',
    city: 'Cincinnati',
    mascot: 'Bengals',
    conference: 'AFC',
    division: 'North',
    primaryColor: '#FB4F14',
    secondaryColor: '#000000',
    offenseRating: 86,
    defenseRating: 82,
    specialTeamsRating: 79,
    playStyle: 'pass_heavy',
  },
  {
    name: 'Cleveland Browns',
    abbreviation: 'CLE',
    city: 'Cleveland',
    mascot: 'Browns',
    conference: 'AFC',
    division: 'North',
    primaryColor: '#311D00',
    secondaryColor: '#FF3C00',
    offenseRating: 74,
    defenseRating: 80,
    specialTeamsRating: 76,
    playStyle: 'run_heavy',
  },
  {
    name: 'Pittsburgh Steelers',
    abbreviation: 'PIT',
    city: 'Pittsburgh',
    mascot: 'Steelers',
    conference: 'AFC',
    division: 'North',
    primaryColor: '#FFB612',
    secondaryColor: '#101820',
    offenseRating: 80,
    defenseRating: 85,
    specialTeamsRating: 81,
    playStyle: 'conservative',
  },

  // ==========================================================
  // AFC SOUTH
  // ==========================================================
  {
    name: 'Houston Texans',
    abbreviation: 'HOU',
    city: 'Houston',
    mascot: 'Texans',
    conference: 'AFC',
    division: 'South',
    primaryColor: '#03202F',
    secondaryColor: '#A71930',
    offenseRating: 85,
    defenseRating: 84,
    specialTeamsRating: 80,
    playStyle: 'balanced',
  },
  {
    name: 'Indianapolis Colts',
    abbreviation: 'IND',
    city: 'Indianapolis',
    mascot: 'Colts',
    conference: 'AFC',
    division: 'South',
    primaryColor: '#002C5F',
    secondaryColor: '#A2AAAD',
    offenseRating: 79,
    defenseRating: 78,
    specialTeamsRating: 80,
    playStyle: 'run_heavy',
  },
  {
    name: 'Jacksonville Jaguars',
    abbreviation: 'JAX',
    city: 'Jacksonville',
    mascot: 'Jaguars',
    conference: 'AFC',
    division: 'South',
    primaryColor: '#006778',
    secondaryColor: '#D7A22A',
    offenseRating: 76,
    defenseRating: 75,
    specialTeamsRating: 74,
    playStyle: 'balanced',
  },
  {
    name: 'Tennessee Titans',
    abbreviation: 'TEN',
    city: 'Tennessee',
    mascot: 'Titans',
    conference: 'AFC',
    division: 'South',
    primaryColor: '#0C2340',
    secondaryColor: '#4B92DB',
    offenseRating: 74,
    defenseRating: 77,
    specialTeamsRating: 75,
    playStyle: 'run_heavy',
  },

  // ==========================================================
  // AFC WEST
  // ==========================================================
  {
    name: 'Denver Broncos',
    abbreviation: 'DEN',
    city: 'Denver',
    mascot: 'Broncos',
    conference: 'AFC',
    division: 'West',
    primaryColor: '#FB4F14',
    secondaryColor: '#002244',
    offenseRating: 80,
    defenseRating: 83,
    specialTeamsRating: 79,
    playStyle: 'balanced',
  },
  {
    name: 'Kansas City Chiefs',
    abbreviation: 'KC',
    city: 'Kansas City',
    mascot: 'Chiefs',
    conference: 'AFC',
    division: 'West',
    primaryColor: '#E31837',
    secondaryColor: '#FFB81C',
    offenseRating: 95,
    defenseRating: 88,
    specialTeamsRating: 85,
    playStyle: 'aggressive',
  },
  {
    name: 'Las Vegas Raiders',
    abbreviation: 'LV',
    city: 'Las Vegas',
    mascot: 'Raiders',
    conference: 'AFC',
    division: 'West',
    primaryColor: '#A5ACAF',
    secondaryColor: '#000000',
    offenseRating: 75,
    defenseRating: 74,
    specialTeamsRating: 73,
    playStyle: 'balanced',
  },
  {
    name: 'Los Angeles Chargers',
    abbreviation: 'LAC',
    city: 'Los Angeles',
    mascot: 'Chargers',
    conference: 'AFC',
    division: 'West',
    primaryColor: '#0080C6',
    secondaryColor: '#FFC20E',
    offenseRating: 84,
    defenseRating: 82,
    specialTeamsRating: 78,
    playStyle: 'pass_heavy',
  },

  // ==========================================================
  // NFC EAST
  // ==========================================================
  {
    name: 'Dallas Cowboys',
    abbreviation: 'DAL',
    city: 'Dallas',
    mascot: 'Cowboys',
    conference: 'NFC',
    division: 'East',
    primaryColor: '#003594',
    secondaryColor: '#869397',
    offenseRating: 82,
    defenseRating: 80,
    specialTeamsRating: 79,
    playStyle: 'pass_heavy',
  },
  {
    name: 'New York Giants',
    abbreviation: 'NYG',
    city: 'New York',
    mascot: 'Giants',
    conference: 'NFC',
    division: 'East',
    primaryColor: '#0B2265',
    secondaryColor: '#A71930',
    offenseRating: 73,
    defenseRating: 76,
    specialTeamsRating: 74,
    playStyle: 'balanced',
  },
  {
    name: 'Philadelphia Eagles',
    abbreviation: 'PHI',
    city: 'Philadelphia',
    mascot: 'Eagles',
    conference: 'NFC',
    division: 'East',
    primaryColor: '#004C54',
    secondaryColor: '#A5ACAF',
    offenseRating: 91,
    defenseRating: 89,
    specialTeamsRating: 84,
    playStyle: 'run_heavy',
  },
  {
    name: 'Washington Commanders',
    abbreviation: 'WAS',
    city: 'Washington',
    mascot: 'Commanders',
    conference: 'NFC',
    division: 'East',
    primaryColor: '#5A1414',
    secondaryColor: '#FFB612',
    offenseRating: 81,
    defenseRating: 79,
    specialTeamsRating: 77,
    playStyle: 'balanced',
  },

  // ==========================================================
  // NFC NORTH
  // ==========================================================
  {
    name: 'Chicago Bears',
    abbreviation: 'CHI',
    city: 'Chicago',
    mascot: 'Bears',
    conference: 'NFC',
    division: 'North',
    primaryColor: '#0B162A',
    secondaryColor: '#C83803',
    offenseRating: 77,
    defenseRating: 80,
    specialTeamsRating: 76,
    playStyle: 'balanced',
  },
  {
    name: 'Detroit Lions',
    abbreviation: 'DET',
    city: 'Detroit',
    mascot: 'Lions',
    conference: 'NFC',
    division: 'North',
    primaryColor: '#0076B6',
    secondaryColor: '#B0B7BC',
    offenseRating: 93,
    defenseRating: 88,
    specialTeamsRating: 83,
    playStyle: 'aggressive',
  },
  {
    name: 'Green Bay Packers',
    abbreviation: 'GB',
    city: 'Green Bay',
    mascot: 'Packers',
    conference: 'NFC',
    division: 'North',
    primaryColor: '#203731',
    secondaryColor: '#FFB612',
    offenseRating: 86,
    defenseRating: 84,
    specialTeamsRating: 81,
    playStyle: 'balanced',
  },
  {
    name: 'Minnesota Vikings',
    abbreviation: 'MIN',
    city: 'Minnesota',
    mascot: 'Vikings',
    conference: 'NFC',
    division: 'North',
    primaryColor: '#4F2683',
    secondaryColor: '#FFC62F',
    offenseRating: 85,
    defenseRating: 82,
    specialTeamsRating: 80,
    playStyle: 'pass_heavy',
  },

  // ==========================================================
  // NFC SOUTH
  // ==========================================================
  {
    name: 'Atlanta Falcons',
    abbreviation: 'ATL',
    city: 'Atlanta',
    mascot: 'Falcons',
    conference: 'NFC',
    division: 'South',
    primaryColor: '#A71930',
    secondaryColor: '#000000',
    offenseRating: 79,
    defenseRating: 77,
    specialTeamsRating: 76,
    playStyle: 'balanced',
  },
  {
    name: 'Carolina Panthers',
    abbreviation: 'CAR',
    city: 'Carolina',
    mascot: 'Panthers',
    conference: 'NFC',
    division: 'South',
    primaryColor: '#0085CA',
    secondaryColor: '#101820',
    offenseRating: 72,
    defenseRating: 74,
    specialTeamsRating: 73,
    playStyle: 'balanced',
  },
  {
    name: 'New Orleans Saints',
    abbreviation: 'NO',
    city: 'New Orleans',
    mascot: 'Saints',
    conference: 'NFC',
    division: 'South',
    primaryColor: '#D3BC8D',
    secondaryColor: '#101820',
    offenseRating: 78,
    defenseRating: 81,
    specialTeamsRating: 80,
    playStyle: 'pass_heavy',
  },
  {
    name: 'Tampa Bay Buccaneers',
    abbreviation: 'TB',
    city: 'Tampa Bay',
    mascot: 'Buccaneers',
    conference: 'NFC',
    division: 'South',
    primaryColor: '#D50A0A',
    secondaryColor: '#34302B',
    offenseRating: 83,
    defenseRating: 81,
    specialTeamsRating: 78,
    playStyle: 'pass_heavy',
  },

  // ==========================================================
  // NFC WEST
  // ==========================================================
  {
    name: 'Arizona Cardinals',
    abbreviation: 'ARI',
    city: 'Arizona',
    mascot: 'Cardinals',
    conference: 'NFC',
    division: 'West',
    primaryColor: '#97233F',
    secondaryColor: '#000000',
    offenseRating: 77,
    defenseRating: 75,
    specialTeamsRating: 74,
    playStyle: 'aggressive',
  },
  {
    name: 'Los Angeles Rams',
    abbreviation: 'LAR',
    city: 'Los Angeles',
    mascot: 'Rams',
    conference: 'NFC',
    division: 'West',
    primaryColor: '#003594',
    secondaryColor: '#FFA300',
    offenseRating: 83,
    defenseRating: 82,
    specialTeamsRating: 79,
    playStyle: 'pass_heavy',
  },
  {
    name: 'San Francisco 49ers',
    abbreviation: 'SF',
    city: 'San Francisco',
    mascot: '49ers',
    conference: 'NFC',
    division: 'West',
    primaryColor: '#AA0000',
    secondaryColor: '#B3995D',
    offenseRating: 90,
    defenseRating: 91,
    specialTeamsRating: 86,
    playStyle: 'run_heavy',
  },
  {
    name: 'Seattle Seahawks',
    abbreviation: 'SEA',
    city: 'Seattle',
    mascot: 'Seahawks',
    conference: 'NFC',
    division: 'West',
    primaryColor: '#002244',
    secondaryColor: '#69BE28',
    offenseRating: 82,
    defenseRating: 80,
    specialTeamsRating: 78,
    playStyle: 'balanced',
  },
];
